package response

// Stable error codes used across handlers and localization mapping.
const (
	CodeMissingAuthorization = "missing authorization"
	CodeMissingToken         = "missing token"
	CodeInvalidToken         = "invalid token"
	CodeInvalidTokenClaims   = "invalid token claims"
	CodeInvalidTokenSubject  = "invalid token subject"
	CodeInsufficientRole     = "insufficient role"

	CodeInvalidRequestBody    = "invalid request body"
	CodeInvalidRequest        = "invalid request"
	CodeInvalidRequestPayload = "invalid request payload"
	CodeValidationError       = "validation error"
	CodeSchoolIDRequired      = "school id required"
	CodeMissingAccountContext = "missing account context"
	CodeAccountIDRequired     = "account id is required"
	CodeAccountNotFound       = "account not found"

	CodeFileIsRequired                  = "file is required"
	CodeFileNotFound                    = "file not found"
	CodeUnableToLoadFile                = "unable to load file"
	CodeUnableToRelayUploadExistingFile = "unable to relay upload existing file"
	CodeUnableToRelayUpload             = "unable to relay upload"
	CodeUnableToInitializeUpload        = "unable to initialize upload"
	CodeUnableToGetDownloadInfo         = "unable to get download info"
	CodeUnableToOpenDownloadStream      = "unable to open download stream"

	CodeAdminAccountNotFound         = "admin account not found"
	CodeAdminAccountRoleNotSupported = "admin account role not supported"
	CodeAdminAccountAlreadyLocked    = "admin account already locked"
	CodeAdminAccountNotLocked        = "admin account not locked"
	CodeAdminPasswordResetPending    = "admin password reset pending"
	CodeAdminAccountOperationFailed  = "admin account operation failed"

	CodeTeacherProfileNotFound          = "teacher profile not found"
	CodeStudentProfileNotFound          = "student profile not found"
	CodeTeacherProfileRequired          = "teacher profile required"
	CodeCourseAccessDenied              = "course access denied"
	CodeMissingAssignmentID             = "missing assignment id"
	CodeMissingCourseChapterID          = "missing course/chapter id"
	CodeChapterNotFound                 = "chapter not found"
	CodeMissingNoteID                   = "missing note id"
	CodeAssignmentNotFound              = "assignment not found"
	CodeNoteNotFound                    = "note not found"
	CodeSubmissionNotFound              = "submission not found"
	CodeSubmissionForbidden             = "submission forbidden"
	CodeInvalidStatus                   = "invalid status"
	CodeInvalidTimeRange                = "invalid time range"
	CodeMissingConversationID           = "missing conversation id"
	CodeMissingReminderID               = "missing reminder id"
	CodeReminderNotFound                = "reminder not found"
	CodeScheduleConflict                = "schedule conflict"
	CodeInvalidSchedule                 = "invalid schedule"
	CodeSchoolIDIsRequired              = "school id is required"
	CodeFailedToResolveSchoolContext    = "failed to resolve school context"
	CodeUnableToExportGrades            = "unable to export grades"
	CodeNotAllowedToAccessNote          = "not allowed to access note"
	CodeDepartmentIDRequired            = "department id is required"
	CodeInvalidCredentials              = "invalid credentials"
	CodeMissingCourseID                 = "missing course id"
	CodeFileTypeTooLong                 = "file type too long"
	CodeFileNameTooLong                 = "file name too long"
	CodeUnableToResolveTeacherProfile   = "unable to resolve teacher profile"
	CodeMissingAssignmentOrSubmissionID = "missing assignment or submission id"
)
