// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.28.2
// source: proto/conversation.proto

package grpcpb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	ConversationService_Stream_FullMethodName         = "/learngo.api.v1.ConversationService/Stream"
	ConversationService_Subscribe_FullMethodName      = "/learngo.api.v1.ConversationService/Subscribe"
	ConversationService_SubscribeInbox_FullMethodName = "/learngo.api.v1.ConversationService/SubscribeInbox"
)

// ConversationServiceClient is the client API for ConversationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConversationServiceClient interface {
	// Subscribe is a server-streaming subscription (web-friendly).
	Subscribe(ctx context.Context, in *JoinConversation, opts ...grpc.CallOption) (ConversationService_SubscribeClient, error)
	// SubscribeInbox aggregates events across all conversations for a user.
	SubscribeInbox(ctx context.Context, in *JoinConversation, opts ...grpc.CallOption) (ConversationService_SubscribeInboxClient, error)
	Stream(ctx context.Context, opts ...grpc.CallOption) (ConversationService_StreamClient, error)
}

type conversationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConversationServiceClient(cc grpc.ClientConnInterface) ConversationServiceClient {
	return &conversationServiceClient{cc}
}

func (c *conversationServiceClient) Subscribe(ctx context.Context, in *JoinConversation, opts ...grpc.CallOption) (ConversationService_SubscribeClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConversationService_ServiceDesc.Streams[1], ConversationService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &conversationServiceSubscribeClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

func (c *conversationServiceClient) SubscribeInbox(ctx context.Context, in *JoinConversation, opts ...grpc.CallOption) (ConversationService_SubscribeInboxClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConversationService_ServiceDesc.Streams[2], ConversationService_SubscribeInbox_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &conversationServiceSubscribeInboxClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

func (c *conversationServiceClient) Stream(ctx context.Context, opts ...grpc.CallOption) (ConversationService_StreamClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConversationService_ServiceDesc.Streams[0], ConversationService_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &conversationServiceStreamClient{ClientStream: stream}
	return x, nil
}

type ConversationService_StreamClient interface {
	Send(*ConversationStreamRequest) error
	Recv() (*ConversationStreamResponse, error)
	grpc.ClientStream
}

type ConversationService_SubscribeClient interface {
	Recv() (*ConversationStreamResponse, error)
	grpc.ClientStream
}

type ConversationService_SubscribeInboxClient interface {
	Recv() (*ConversationStreamResponse, error)
	grpc.ClientStream
}

type conversationServiceSubscribeClient struct {
	grpc.ClientStream
}

func (x *conversationServiceSubscribeClient) Recv() (*ConversationStreamResponse, error) {
	m := new(ConversationStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

type conversationServiceSubscribeInboxClient struct {
	grpc.ClientStream
}

func (x *conversationServiceSubscribeInboxClient) Recv() (*ConversationStreamResponse, error) {
	m := new(ConversationStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

type conversationServiceStreamClient struct {
	grpc.ClientStream
}

func (x *conversationServiceStreamClient) Send(m *ConversationStreamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *conversationServiceStreamClient) Recv() (*ConversationStreamResponse, error) {
	m := new(ConversationStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ConversationServiceServer is the server API for ConversationService service.
// All implementations must embed UnimplementedConversationServiceServer
// for forward compatibility
type ConversationServiceServer interface {
	// Subscribe is a server-streaming subscription (web-friendly).
	Subscribe(*JoinConversation, ConversationService_SubscribeServer) error
	// SubscribeInbox aggregates events across all conversations for a user.
	SubscribeInbox(*JoinConversation, ConversationService_SubscribeInboxServer) error
	Stream(ConversationService_StreamServer) error
	mustEmbedUnimplementedConversationServiceServer()
}

// UnimplementedConversationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedConversationServiceServer struct {
}

func (UnimplementedConversationServiceServer) Subscribe(*JoinConversation, ConversationService_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedConversationServiceServer) SubscribeInbox(*JoinConversation, ConversationService_SubscribeInboxServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeInbox not implemented")
}
func (UnimplementedConversationServiceServer) Stream(ConversationService_StreamServer) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedConversationServiceServer) mustEmbedUnimplementedConversationServiceServer() {}

// UnsafeConversationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConversationServiceServer will
// result in compilation errors.
type UnsafeConversationServiceServer interface {
	mustEmbedUnimplementedConversationServiceServer()
}

func RegisterConversationServiceServer(s grpc.ServiceRegistrar, srv ConversationServiceServer) {
	s.RegisterService(&ConversationService_ServiceDesc, srv)
}

func _ConversationService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(JoinConversation)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConversationServiceServer).Subscribe(m, &conversationServiceSubscribeServer{ServerStream: stream})
}

func _ConversationService_SubscribeInbox_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(JoinConversation)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConversationServiceServer).SubscribeInbox(m, &conversationServiceSubscribeInboxServer{ServerStream: stream})
}

func _ConversationService_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ConversationServiceServer).Stream(&conversationServiceStreamServer{ServerStream: stream})
}

type ConversationService_SubscribeServer interface {
	Send(*ConversationStreamResponse) error
	grpc.ServerStream
}

type conversationServiceSubscribeServer struct {
	grpc.ServerStream
}

func (x *conversationServiceSubscribeServer) Send(m *ConversationStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

type ConversationService_SubscribeInboxServer interface {
	Send(*ConversationStreamResponse) error
	grpc.ServerStream
}

type conversationServiceSubscribeInboxServer struct {
	grpc.ServerStream
}

func (x *conversationServiceSubscribeInboxServer) Send(m *ConversationStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

type ConversationService_StreamServer interface {
	Send(*ConversationStreamResponse) error
	Recv() (*ConversationStreamRequest, error)
	grpc.ServerStream
}

type conversationServiceStreamServer struct {
	grpc.ServerStream
}

func (x *conversationServiceStreamServer) Send(m *ConversationStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *conversationServiceStreamServer) Recv() (*ConversationStreamRequest, error) {
	m := new(ConversationStreamRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ConversationService_ServiceDesc is the grpc.ServiceDesc for ConversationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConversationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "learngo.api.v1.ConversationService",
	HandlerType: (*ConversationServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _ConversationService_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Subscribe",
			Handler:       _ConversationService_Subscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeInbox",
			Handler:       _ConversationService_SubscribeInbox_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/conversation.proto",
}
